### PR TITLE
Added logic to set sensitivity for trackpoint

### PR DESCRIPTION
**Pull request by DrCrally**
You asked for help writing the logic and I'm not sure how you wanted, so I've opted to remove the use of libinput and directly write the value to the device file.

I've set the minimum and maximum values to 30 and 220 respectively, as I feel those are the two extremes which someone might still use.

To save the value, the program must be run with root privileges as it needs write permission for the device file in /sys/devices/

### CODE REVIEW

**Comment by DrCrally** [comment]
Also, I've fixed some formatting and renamed a few things.

**Comment by CountryTk** [comment]
I don't think writing the values straight to the device is a good idea since the user has to do `sudo su` and then execute the command, otherwise it's just going to say permission denied.

**Comment by DrCrally** [comment]
They don't need to do `sudo su`, they only need to run the program with `sudo`, e.g. `sudo simple_sens`.

**Comment by DrCrally** [comment]
> I don't think writing the values straight to the device is a good idea since the user has to do `sudo su` and then execute the command, otherwise it's just going to say permission denied.

They don't need to do `sudo su`, they only need to run the program with `sudo`, e.g. `sudo simple_sens`.

**Comment by DrCrally** [comment]
I should also note that this is the standard way to do it.
See https://www.thinkwiki.org/wiki/How_to_configure_the_TrackPoint

I'm actually not sure if there even is another way to set the trackpoint sensitivity.

**Comment by CountryTk** [comment]
I used to change my sensitivity like that and I always had to sudo su in order to have the permission to write it.

**Comment by DrCrally** [comment]
I'm going to give you the benefit of the doubt and assume you're unfamiliar with the command line and also that you're referring to something like
`echo "120" > /sys/devices/path/to/file`
`sh: Permission denied`
(The picture you linked was blank so I'm not sure)
In this case, it's your shell that handles redirection. It's trying to open the file under _your_ permissions and not those of the process you're running under sudo.
If you run vim as sudo and edit the file, you'll find that it works as expected.
Or even,
`sudo sh -c "echo '120' >> /sys/devices/path/to/file"`

**Comment by CountryTk** [comment]
Oh...
Anyway, what are the benefits of making a program need higher permissions when it works without them.

**Comment by DrCrally** [comment]
How would it work without them? What is the alternative method of setting the sensitivity without modifying its device file?

**Comment by CountryTk** [comment]
Right now it my program is basically a wrapper around the command `xinput --set-prop <device id> 'libinput Accel Speed' <acceleration factor>`

**Comment by DrCrally** [comment]
> Right now it my program is basically a wrapper around the command `xinput --set-prop <device id> 'libinput Accel Speed' <acceleration factor>`

Running this command gives me an error on my machine. Possibly I'm doing something, do you have an example I could run and test?

**Comment by CountryTk** [comment]
first xinput list and find a string that says IBM trackpoint and then look at the id that is assigned to it:
image
Then use that id to write the command

`xinput --set-prop 12 'libinput Accel Speed' 0.01`

The accel speed values are between 0 and 1

**Comment by DrCrally** [comment]
Running this command does not change the speed of my trackpoint cursor.

**Comment by CountryTk** [comment]
Try setting it to 1 and then 0.1, it should make a difference.
Is there any output to the CMD?

**Comment by DrCrally** [comment]
The command executes sucessfully. There is no difference in speed, or if there is it's too little to notice.
Even when changing between .01 and 1.0

Also afaik, you don't need to scan the output and find the id, you could simplify the command to
`xinput set-prop "TPPS/2 IBM TrackPoint" 'libinput Accel Speed' 0.01`

**Comment by CountryTk** [comment]
I tested this out on T440p, T420, X61, T400, X200T and on my T60 and to me it seemed like a big change, idk might be personal preference.

**Comment by DrCrally** [comment]
> might be personal preference

This is not what personal preference means.

Also, I'm testing this on an x220 and the command has no effect on the speed of my trackpoint or, if it does, it's barely noticeable. It additionally introduces an unneeded dependency even if it did work.

**Pull request closed without merging**
